export const SET_CARD_NUMBER = "SET_CARD_NUMBER";
export const SET_EXPIRATION_DATE = "SET_EXPIRATION_DATE";
export const SET_SECURITY_CODE = "SET_SECURITY_CODE";
export const SET_CARDHOLDER_NAME = "SET_CARDHOLDER_NAME";
export const SUBMIT_PAYMENT_DETAILS = "SUBMIT_PAYMENT_DETAILS";
export const SET_ERROR = "SET_ERROR";
